### Creating NumPy arrays

In [1]:
import numpy as np
arr1 = np.array([1, 2, 3, 4, 5])
print("1D array:", arr1)
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print("2D array:")
print(arr2)

1D array: [1 2 3 4 5]
2D array:
[[1 2 3]
 [4 5 6]]


### Vectorized operations

In [2]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([10, 20, 30, 40, 50])
print("Addition:", a + b)
print("Multiplication:", a * b)

Addition: [11 22 33 44 55]
Multiplication: [ 10  40  90 160 250]


### Predefined arrays

In [3]:
print(np.zeros((3, 4)))
print(np.ones((2, 5)))
print(np.arange(0, 10, 2))
print(np.linspace(0, 1, 5))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]


### Slicing and indexing

In [4]:
matrix = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
submatrix = matrix[1:4, 1:4]
print("Submatrix:")
print(submatrix)
element = matrix[1,2]
print("Element at (2,3):", element)

Submatrix:
[[ 6  7  8]
 [10 11 12]
 [14 15 16]]
Element at (2,3): 7


### Broadcasting example

In [5]:
mat = np.array([[1,2,3],[4,5,6],[7,8,9]])
vec = np.array([1,0,-1])
print("Broadcasting result:")
print(mat - vec)

Broadcasting result:
[[ 0  2  4]
 [ 3  5  7]
 [ 6  8 10]]


### Mathematical functions

In [6]:
angles = np.linspace(0, np.pi, 5)
print("Angles:", angles)
print("Sine values:", np.sin(angles))
print("Exponential values:", np.exp(np.array([0, 1, 2])))

Angles: [0.         0.78539816 1.57079633 2.35619449 3.14159265]
Sine values: [0.00000000e+00 7.07106781e-01 1.00000000e+00 7.07106781e-01
 1.22464680e-16]
Exponential values: [1.         2.71828183 7.3890561 ]
